version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_BASE_URL=http://localhost:8000
    volumes:
      - ./data:/app/data
    restart: unless-stopped
